#!/usr/bin/env python

import rospy
import requests
import datetime

import sensor_msgs.msg

rospy.init_node("task_communication")
try:
	host = rospy.get_param("Host")
	teamid = rospy.get_param("TeamID")
	course = rospy.get_param("Course")
except KeyError:
	rospy.logfatal("Check if Driver has run once for the heartbeat to work")

rospy.Subscriber("/boat_fix", sensor_msgs.msg.NavSatFix, callback)
rospy.spin()




#heartbeat(16.0405, 17.00)